[package]
name = "mathyml"
version = "0.1.0"
compiler = "0.13.0"
entrypoint = "src/lib.typ"
authors = ["Akida"]
license = "MIT"
repository = "https://codeberg.org/akida/mathyml"
description = "Convert your equations to MathML"
categories = ["integration", "utility"]
keywords = ["MathML", "MathML Core", "html"]
exclude = ["examples", "docs"]
